name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.12

      - name: Install dependencies (Windows)
        run: bun install
        shell: pwsh
        if: runner.os == 'Windows'
      - name: Install dependencies (Unix)
        run: bun install
        if: runner.os != 'Windows'

      - name: Run tests (Windows)
        run: bun test
        shell: pwsh
        if: runner.os == 'Windows'
      - name: Run tests (Unix)
        run: bun test
        if: runner.os != 'Windows'

  prettier:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies (Windows)
        run: bun install
        shell: pwsh
        if: runner.os == 'Windows'
      - name: Install dependencies (Unix)
        run: bun install
        if: runner.os != 'Windows'

      - name: Run prettier check (Windows)
        run: bun run format:check
        shell: pwsh
        if: runner.os == 'Windows'
      - name: Run prettier check (Unix)
        run: bun run format:check
        if: runner.os != 'Windows'

  typecheck:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.12

      - name: Install dependencies (Windows)
        run: bun install
        shell: pwsh
        if: runner.os == 'Windows'
      - name: Install dependencies (Unix)
        run: bun install
        if: runner.os != 'Windows'

      - name: Run TypeScript type check (Windows)
        run: bun run typecheck
        shell: pwsh
        if: runner.os == 'Windows'
      - name: Run TypeScript type check (Unix)
        run: bun run typecheck
        if: runner.os != 'Windows'
